# coding: utf-8

"""
    API Doc

    Onedoc is an innovative API solution for developers, offering a simple and secure way to create and manage PDF documents using familiar technologies like React.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from one_doc_python_sdk.paths.api_docs_generate.post import GeneratePdfFromBucket
from one_doc_python_sdk.paths.api_docs_initiate.post import RenderingBucket
from one_doc_python_sdk.apis.tags.document_api_raw import DocumentApiRaw


class DocumentApi(
    GeneratePdfFromBucket,
    RenderingBucket,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DocumentApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DocumentApiRaw(api_client)
