# coding: utf-8

"""
    API Doc

    Onedoc is an innovative API solution for developers, offering a simple and secure way to create and manage PDF documents using familiar technologies like React.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from one_doc_python_sdk import OneDoc

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        onedoc = OneDoc(
        
                        api_key_auth = 'YOUR_API_KEY',
        )
        self.assertIsNotNone(onedoc)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
