# coding: utf-8

"""
    API Doc

    Onedoc is an innovative API solution for developers, offering a simple and secure way to create and manage PDF documents using familiar technologies like React.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import one_doc_python_sdk
from one_doc_python_sdk.model.document_generate_pdf_from_bucket_request import DocumentGeneratePdfFromBucketRequest
from one_doc_python_sdk import configuration


class TestDocumentGeneratePdfFromBucketRequest(unittest.TestCase):
    """DocumentGeneratePdfFromBucketRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
