# coding: utf-8

"""
    API Doc

    Onedoc is an innovative API solution for developers, offering a simple and secure way to create and manage PDF documents using familiar technologies like React.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import one_doc_python_sdk
from one_doc_python_sdk.model.document_rendering_bucket_response_signed_urls import DocumentRenderingBucketResponseSignedUrls
from one_doc_python_sdk import configuration


class TestDocumentRenderingBucketResponseSignedUrls(unittest.TestCase):
    """DocumentRenderingBucketResponseSignedUrls unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
