# coding: utf-8

"""
    API Doc

    Onedoc is an innovative API solution for developers, offering a simple and secure way to create and manage PDF documents using familiar technologies like React.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from one_doc_python_sdk import schemas  # noqa: F401


class DocumentRenderingBucketResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            uploadURL = schemas.StrSchema
            username = schemas.StrSchema
            password = schemas.StrSchema
            bucket = schemas.StrSchema
        
            @staticmethod
            def signedUrls() -> typing.Type['DocumentRenderingBucketResponseSignedUrls']:
                return DocumentRenderingBucketResponseSignedUrls
            __annotations__ = {
                "uploadURL": uploadURL,
                "username": username,
                "password": password,
                "bucket": bucket,
                "signedUrls": signedUrls,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["uploadURL"]) -> MetaOapg.properties.uploadURL: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["username"]) -> MetaOapg.properties.username: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["password"]) -> MetaOapg.properties.password: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bucket"]) -> MetaOapg.properties.bucket: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["signedUrls"]) -> 'DocumentRenderingBucketResponseSignedUrls': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["uploadURL", "username", "password", "bucket", "signedUrls", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["uploadURL"]) -> typing.Union[MetaOapg.properties.uploadURL, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["username"]) -> typing.Union[MetaOapg.properties.username, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["password"]) -> typing.Union[MetaOapg.properties.password, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bucket"]) -> typing.Union[MetaOapg.properties.bucket, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["signedUrls"]) -> typing.Union['DocumentRenderingBucketResponseSignedUrls', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["uploadURL", "username", "password", "bucket", "signedUrls", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        uploadURL: typing.Union[MetaOapg.properties.uploadURL, str, schemas.Unset] = schemas.unset,
        username: typing.Union[MetaOapg.properties.username, str, schemas.Unset] = schemas.unset,
        password: typing.Union[MetaOapg.properties.password, str, schemas.Unset] = schemas.unset,
        bucket: typing.Union[MetaOapg.properties.bucket, str, schemas.Unset] = schemas.unset,
        signedUrls: typing.Union['DocumentRenderingBucketResponseSignedUrls', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DocumentRenderingBucketResponse':
        return super().__new__(
            cls,
            *args,
            uploadURL=uploadURL,
            username=username,
            password=password,
            bucket=bucket,
            signedUrls=signedUrls,
            _configuration=_configuration,
            **kwargs,
        )

from one_doc_python_sdk.model.document_rendering_bucket_response_signed_urls import DocumentRenderingBucketResponseSignedUrls
