# coding: utf-8

"""
    API Doc

    Onedoc is an innovative API solution for developers, offering a simple and secure way to create and manage PDF documents using familiar technologies like React.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from one_doc_python_sdk import schemas  # noqa: F401


class DocumentRenderingBucketRequestAssets(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)

    Array of assets to generate signed URLs for.
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['DocumentRenderingBucketRequestAssetsItem']:
            return DocumentRenderingBucketRequestAssetsItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['DocumentRenderingBucketRequestAssetsItem'], typing.List['DocumentRenderingBucketRequestAssetsItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'DocumentRenderingBucketRequestAssets':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'DocumentRenderingBucketRequestAssetsItem':
        return super().__getitem__(i)

from one_doc_python_sdk.model.document_rendering_bucket_request_assets_item import DocumentRenderingBucketRequestAssetsItem
