# coding: utf-8
"""
    API Doc

    Onedoc is an innovative API solution for developers, offering a simple and secure way to create and manage PDF documents using familiar technologies like React.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from one_doc_python_sdk.client_custom import ClientCustom
from one_doc_python_sdk.configuration import Configuration
from one_doc_python_sdk.api_client import ApiClient
from one_doc_python_sdk.type_util import copy_signature
from one_doc_python_sdk.apis.tags.document_api import DocumentApi



class OneDoc(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.document: DocumentApi = DocumentApi(api_client)
