# coding: utf-8

"""
    API Doc

    Onedoc is an innovative API solution for developers, offering a simple and secure way to create and manage PDF documents using familiar technologies like React.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class DocumentRenderingBucketResponseSignedUrlsItem(BaseModel):
    # The relative path of the asset in the bucket.
    path: typing.Optional[str] = Field(None, alias='path')

    # Access token for the signed Url.
    token: typing.Optional[str] = Field(None, alias='token')

    # The signed URL to the bucket for the asset in path.
    signed_url: typing.Optional[str] = Field(None, alias='signedUrl')
    class Config:
        arbitrary_types_allowed = True
